"""Constants for auditable actions.

Naming convention: SUBJECT_VERB or RESOURCE_ACTION, uppercase.
"""

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"
LOGOUT = "LOGOUT"
TOKEN_REVOKED = "TOKEN_REVOKED"

PASSWORD_CHANGE = "PASSWORD_CHANGE"
PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_FAILED"
PASSWORD_RESET = "PASSWORD_RESET"

USER_CREATE = "USER_CREATE"
USER_UPDATE = "USER_UPDATE"
USER_DELETE = "USER_DELETE"
ROLE_CHANGE = "ROLE_CHANGE"
USER_DEACTIVATE = "USER_DEACTIVATE"
USER_ACTIVATE = "USER_ACTIVATE"

# Cron jobs (Phase 3)
CRON_JOB_CREATED = "CRON_JOB_CREATED"
CRON_JOB_UPDATED = "CRON_JOB_UPDATED"
CRON_JOB_ENABLED = "CRON_JOB_ENABLED"
CRON_JOB_DISABLED = "CRON_JOB_DISABLED"
CRON_JOB_DELETED = "CRON_JOB_DELETED"

# Scripts (Phase 4)
SCRIPT_CREATED = "SCRIPT_CREATED"
SCRIPT_UPDATED = "SCRIPT_UPDATED"
SCRIPT_ENABLED = "SCRIPT_ENABLED"
SCRIPT_DISABLED = "SCRIPT_DISABLED"
SCRIPT_DELETED = "SCRIPT_DELETED"

# Executions (Phase 4)
EXECUTION_STARTED = "EXECUTION_STARTED"
EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
EXECUTION_FAILED = "EXECUTION_FAILED"
EXECUTION_TIMED_OUT = "EXECUTION_TIMED_OUT"

# Scheduler (Phase 5)
EXECUTION_SKIPPED = "EXECUTION_SKIPPED"
