"""Constants for auditable actions.

Naming convention: SUBJECT_VERB or RESOURCE_ACTION, uppercase.
"""

LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"
LOGOUT = "LOGOUT"
TOKEN_REVOKED = "TOKEN_REVOKED"

PASSWORD_CHANGE = "PASSWORD_CHANGE"
PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_FAILED"
PASSWORD_RESET = "PASSWORD_RESET"

USER_CREATE = "USER_CREATE"
USER_UPDATE = "USER_UPDATE"
USER_DELETE = "USER_DELETE"
ROLE_CHANGE = "ROLE_CHANGE"
USER_DEACTIVATE = "USER_DEACTIVATE"
USER_ACTIVATE = "USER_ACTIVATE"
